/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    BCarousel: typeof import('bootstrap-vue-next')['BCarousel']
    BCarouselSlide: typeof import('bootstrap-vue-next')['BCarouselSlide']
    Company: typeof import('./src/components/about/Company.vue')['default']
    Copyright: typeof import('./src/components/footer/Copyright.vue')['default']
    Footer: typeof import('./src/components/footer/Footer.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    NaviHeader: typeof import('./src/components/header/NaviHeader.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Timeline: typeof import('./src/components/about/Timeline.vue')['default']
    TimeLine: typeof import('./src/components/about/TimeLine.vue')['default']
    TopHeader: typeof import('./src/components/header/TopHeader.vue')['default']
  }
}
