/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    BackToTop: typeof import('./src/components/tools/BackToTop.vue')['default']
    BFormSelect: typeof import('bootstrap-vue-next')['BFormSelect']
    Company: typeof import('./src/components/about/Company.vue')['default']
    Copyright: typeof import('./src/components/footer/Copyright.vue')['default']
    Counter: typeof import('./src/components/home/Counter.vue')['default']
    Culture: typeof import('./src/components/about/Culture.vue')['default']
    Detail: typeof import('./src/components/products/Detail.vue')['default']
    Feedback: typeof import('./src/components/contact/Feedback.vue')['default']
    Footer: typeof import('./src/components/footer/Footer.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    List: typeof import('./src/components/products/List.vue')['default']
    Method: typeof import('./src/components/contact/Method.vue')['default']
    NaviHeader: typeof import('./src/components/header/NaviHeader.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Timeline: typeof import('./src/components/about/Timeline.vue')['default']
    TopHeader: typeof import('./src/components/header/TopHeader.vue')['default']
  }
}
