/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    BackToTop: typeof import('./src/components/tools/BackToTop.vue')['default']
    BBadge: typeof import('bootstrap-vue-next')['BBadge']
    BButton: typeof import('bootstrap-vue-next')['BButton']
    BFormSelect: typeof import('bootstrap-vue-next')['BFormSelect']
    BListGroup: typeof import('bootstrap-vue-next')['BListGroup']
    BListGroupItem: typeof import('bootstrap-vue-next')['BListGroupItem']
    BModal: typeof import('bootstrap-vue-next')['BModal']
    BOffcanvas: typeof import('bootstrap-vue-next')['BOffcanvas']
    BOverlay: typeof import('bootstrap-vue-next')['BOverlay']
    BPagination: typeof import('bootstrap-vue-next')['BPagination']
    Company: typeof import('./src/components/about/Company.vue')['default']
    Copyright: typeof import('./src/components/footer/Copyright.vue')['default']
    Counter: typeof import('./src/components/home/Counter.vue')['default']
    Culture: typeof import('./src/components/about/Culture.vue')['default']
    Footer: typeof import('./src/components/footer/Footer.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    List: typeof import('./src/components/news/List.vue')['default']
    Main: typeof import('./src/components/news/Main.vue')['default']
    Message: typeof import('./src/components/contact/Message.vue')['default']
    Method: typeof import('./src/components/contact/Method.vue')['default']
    NaviHeader: typeof import('./src/components/header/NaviHeader.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Side: typeof import('./src/components/news/Side.vue')['default']
    Timeline: typeof import('./src/components/about/Timeline.vue')['default']
    TopHeader: typeof import('./src/components/header/TopHeader.vue')['default']
  }
}
